language: java
sudo: false
jdk:
  - oraclejdk8
cache:
  directories:
  - $HOME/.m2
before_install:
  - chmod +x mvnw
install:
  - ./mvnw install -DskipTests=false -Dmaven.javadoc.skip=true -B -V
script:
  - mvn clean test