version: '3'
services:
  web:
    build: .
    depends_on:
      - elasticsearch
  elasticsearch:
    image: elasticsearch:2.4.6
    volumes:
      - "./src/main/resources/custom_elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml"
    expose:
      - "9200"
      - "9300"
    ports:
      - "9200:9200"
      - "9300:9300"