version: '3'
services:
  web:
    build: .
    links:
      - elasticsearch
  elasticsearch:
    image: elasticsearch:2.4.6
    volumes:
      - "/src/main/resources/custom_elasticsearch.yml:/usr/share/elasticearch/config/elasticsearch.yml"
    expose:
      - "9200"
      - "9300"
    ports:
      - "9200:9200"
      - "9300:9300"